# Using autodiff to check gradient/Hessians

In [1]:
using Revise
using QuasiCopula
using DataFrames, Random, GLM
using LinearAlgebra
using LinearAlgebra: BlasReal, copytri!
using ToeplitzMatrices
using BenchmarkTools
using SnpArrays
using ForwardDiff
using FastDifferentiation
# using MendelPlots
ENV["COLUMNS"] = 240

BLAS.set_num_threads(1)
Threads.nthreads()

# simulate PLINK data where each SNP has at least min_ma copies of the alt allele
function simulate_random_snparray(s::Union{String, UndefInitializer}, n::Int64,
        p::Int64, mafs::Vector{Float64}; min_ma::Int = 1)
    all(0.0 .<= mafs .<= 0.5) || throw(ArgumentError("vector of minor allele frequencies must be in (0, 0.5)"))
#     any(mafs .<= 0.0005) && @warn("Provided minor allele frequencies contain entries smaller than 0.0005, simulation may take long if sample size is small and min_ma = $min_ma is large")

    #first simulate a random {0, 1, 2} matrix with each SNP drawn from Binomial(2, r[i])
    A1 = BitArray(undef, n, p) 
    A2 = BitArray(undef, n, p) 
    for j in 1:p
        minor_alleles = 0
        maf = mafs[j]
        while minor_alleles <= min_ma
            for i in 1:n
                A1[i, j] = rand(Bernoulli(maf))
                A2[i, j] = rand(Bernoulli(maf))
            end
            minor_alleles = sum(view(A1, :, j)) + sum(view(A2, :, j))
        end
    end

    #fill the SnpArray with the corresponding x_tmp entry
    return _make_snparray(s, A1, A2)
end


# function simulate_random_snparray(s::Union{String, UndefInitializer}, n::Int64,
#     p::Int64; mafs::Vector{Float64}=zeros(Float64, p), min_ma::Int = 5)

#     #first simulate a random {0, 1, 2} matrix with each SNP drawn from Binomial(2, r[i])
#     A1 = BitArray(undef, n, p) 
#     A2 = BitArray(undef, n, p) 
#     for j in 1:p
#         minor_alleles = 0
#         maf = 0
#         while minor_alleles <= min_ma
#             maf = 0.5rand()
#             for i in 1:n
#                 A1[i, j] = rand(Bernoulli(maf))
#                 A2[i, j] = rand(Bernoulli(maf))
#             end
#             minor_alleles = sum(view(A1, :, j)) + sum(view(A2, :, j))
#         end
#         mafs[j] = maf
#     end

#     #fill the SnpArray with the corresponding x_tmp entry
#     return _make_snparray(s, A1, A2)
# end

function _make_snparray(s::Union{String, UndefInitializer}, A1::BitArray, A2::BitArray)
    n, p = size(A1)
    x = SnpArray(s, n, p)
    for i in 1:(n*p)
        c = A1[i] + A2[i]
        if c == 0
            x[i] = 0x00
        elseif c == 1
            x[i] = 0x02
        elseif c == 2
            x[i] = 0x03
        else
            throw(MissingException("matrix shouldn't have missing values!"))
        end
    end
    return x
end

LoadError: ArgumentError: Package Revise not found in current path.
- Run `import Pkg; Pkg.add("Revise")` to install the Revise package.

In [6]:
function simulate_VC_longitudinal(;
    n = 1000, # sample size
    d_min = 1, # min number of observations per sample
    d_max = 5, # max number of observations per sample
    p = 3, # number of nongenetic covariates, including intercept
    m = 1, # number of variance components
    q = 1000, # number of SNPs
    k = 10, # number of causal SNPs
    maf = 0.5rand(),
    causal_snp_β = 0.5rand(),
    seed = 2022,
    y_distribution = Bernoulli,
    T = Float64,
    )
    Random.seed!(seed)
    m == 1 || m == 2 || error("m (number of VC) must be 1 or 2")
    
    # non-genetic effect sizes
    Random.seed!(seed)
#     βtrue = [1.0; rand(-0.05:0.1:0.05, p-1)]
    βtrue = [1.0; rand(-0.5:1:0.5, p-1)]
#     βtrue = [1.0; rand(-5:10:5, p-1) .* rand(Uniform(0, 5), p-1)]
    dist = y_distribution()
    link = canonicallink(dist)
    Dist = typeof(dist)
    Link = typeof(link)

    # variance components
    θtrue = fill(0.1, m)

    # simulate (nongenetic) design matrices
    Random.seed!(seed)
    X_full = Matrix{Float64}[]
    for i in 1:n
        nobs = rand(d_min:d_max) # number of obs for this sample
        push!(X_full, hcat(ones(nobs), randn(nobs, p - 1)))
    end
    
    # simulate causal alleles
    Random.seed!(seed)
    γtrue = zeros(q)
#     γtrue[1:k] .= rand([-0.2, 0.2], k)
    γtrue[1:k] .= causal_snp_β
    shuffle!(γtrue)
    
    # set minor allele freq
    mafs = fill(maf, q)
    
    # simulate random SnpArray with q SNPs with prespecified maf
    Random.seed!(seed)
    G = simulate_random_snparray(undef, n, q, mafs)
    Gfloat = convert(Matrix{T}, G, center=true, scale=false)
    
    # effect of causal alleles
    η_G = Gfloat * γtrue

    # simulate phenotypes
    if y_distribution == Normal
        τtrue = 10.0
        σ2 = inv(τtrue)
        σ = sqrt(σ2)
        obs = Vector{GaussianCopulaVCObs{T}}(undef, n)
        for i in 1:n
            # data matrix
            X = X_full[i]
            η = X * βtrue
            η .+= η_G[i] # add genetic effects
            μ = GLM.linkinv.(link, η)
            vecd = Vector{ContinuousUnivariateDistribution}(undef, size(X, 1))
            # VC matrices
            V1 = ones(size(X, 1), size(X, 1))
            V2 = Matrix(I, size(X, 1), size(X, 1))
            Γ = m == 1 ? θtrue[1] * V1 : θtrue[1] * V1 + θtrue[2] * V2
            for i in 1:size(X, 1)
                vecd[i] = y_distribution(μ[i], σ)
            end
            nonmixed_multivariate_dist = NonMixedMultivariateDistribution(vecd, Γ)
            # simuate single vector y
            y = Vector{T}(undef, size(X, 1))
            res = Vector{T}(undef, size(X, 1))
            rand(nonmixed_multivariate_dist, y, res)
            V = m == 1 ? [V1] : [V1, V2]
            obs[i] = GaussianCopulaVCObs(y, X, V)
        end
        qc_model = GaussianCopulaVCModel(obs)
    else
        obs = Vector{GLMCopulaVCObs{T, Dist, Link}}(undef, n)
        for i in 1:n
            # data matrix
            X = X_full[i]
            η = X * βtrue
            η .+= η_G[i] # add genetic effects
            μ = GLM.linkinv.(link, η)
            # VC matrices
            V1 = ones(size(X, 1), size(X, 1))
            V2 = Matrix(I, size(X, 1), size(X, 1))
            Γ = m == 1 ? θtrue[1] * V1 : θtrue[1] * V1 + θtrue[2] * V2
            vecd = Vector{DiscreteUnivariateDistribution}(undef, size(X, 1))
            for i in 1:size(X, 1)
                vecd[i] = y_distribution(μ[i])
            end
            nonmixed_multivariate_dist = NonMixedMultivariateDistribution(vecd, Γ)
            # simuate single vector y
            y = Vector{T}(undef, size(X, 1))
            res = Vector{T}(undef, size(X, 1))
            rand(nonmixed_multivariate_dist, y, res)
            V = m == 1 ? [V1] : [V1, V2]
            obs[i] = GLMCopulaVCObs(y, X, V, dist, link)
        end
        qc_model = GLMCopulaVCModel(obs)
    end
    return qc_model, G, βtrue, θtrue, γtrue
end

k = 0 # number of causal SNPs
maf = 0.3

qc_model, G, βtrue, θtrue, γtrue = simulate_VC_longitudinal(
    n = 5000, # sample size
    d_min = 5, # min number of observations per sample
    d_max = 5, # max number of observations per sample
    p = 3, # number of fixed effects, including intercept
    m = 2, # number of variance components
    q = 1000, # number of SNPs
    k = k, # number of causal SNPs
    seed = 123,
    y_distribution = Normal,
    T = Float64,
    maf = maf,
    causal_snp_β = 0.2
)

@show qc_model;

qc_model = Quasi-Copula Variance Component Model
  * base distribution: Normal
  * link function: IdentityLink
  * number of clusters: 5000
  * cluster size min, max: 5, 5
  * number of variance components: 2
  * number of fixed effects: 3



In [7]:
@time optm = QuasiCopula.fit!(qc_model,
    Ipopt.IpoptSolver(
        print_level = 5, 
        tol = 10^-6, 
        max_iter = 100,
        accept_after_max_steps = 4,
        warm_start_init_point="yes", 
        limited_memory_max_history = 6, # default value
        hessian_approximation = "limited-memory",
#         derivative_test="second-order"
    )
);

This is Ipopt version 3.13.4, running with linear solver mumps.
NOTE: Other linear solvers might be more efficient (see Ipopt documentation).

Number of nonzeros in equality constraint Jacobian...:        0
Number of nonzeros in inequality constraint Jacobian.:        0
Number of nonzeros in Lagrangian Hessian.............:        0

Total number of variables............................:        6
                     variables with only lower bounds:        3
                variables with lower and upper bounds:        0
                     variables with only upper bounds:        0
Total number of equality constraints.................:        0
Total number of inequality constraints...............:        0
        inequality constraints with only lower bounds:        0
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:        0

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  

┌ Warning: Optimization unsuccesful; got UserLimit
└ @ QuasiCopula ~/.julia/dev/QuasiCopula/src/parameter_estimation/fit_gaussian_vc.jl:36


In [8]:
@show βtrue
@show qc_model.β
@show qc_model.∇β

@show θtrue
@show qc_model.θ
@show qc_model.∇θ;

βtrue = [1.0, 0.5, 0.5]
qc_model.β = [1.0032180635239134, 0.499615300082326, 0.504938907098027]
qc_model.∇β = [-278.53740082307894, 191.34914908943682, -625.1459617695186]
θtrue = [0.1, 0.1]
qc_model.θ = [0.09077503254060787, 0.15782904820275423]
qc_model.∇θ = [105.40722800120844, -15.648559418232566]


## Is $\nabla_\beta res$ calculated correctly? 

We can check using ForwardDiff

The function is 

$$res_{ij}(\beta) = \frac{y_{ij} - \mu_{ij}}{\sqrt{\sigma_{ij}^2(\beta)}}$$

### Normal

Assumes y, X are given. We calculate the residuals for just 1 sample

In [6]:
# sample data
X = qc_model.data[1].X # d by p
y = qc_model.data[1].y # d by 1

# objective
function resβ(β)
    η = X * β # d by 1
    μ = GLM.linkinv.(IdentityLink(), η)
    varμ = GLM.glmvar.(Normal(), μ)
    return (y - μ) ./ sqrt.(varμ) # d by 1
end

# mathematical gradient
function ∇resβ(β)
    d, p = size(X)
    ∇resβ = zeros(d, p)
    for i in 1:p, j in 1:d
        ∇resβ[j, i] = -X[j, i]
    end
    return ∇resβ # d × p
end

# autodiff gradient
∇resβ_autodiff = x -> ForwardDiff.jacobian(resβ, x)

# random beta vector
β = rand(size(qc_model.data[1].X, 2))

# check objective
@show resβ(β)

# compare mathematical and numerical gradient
[vec(∇resβ(β)) vec(∇resβ_autodiff(β))]

resβ(β) = [0.2930300844455167, 0.28075955722544743, -0.31663142469334576, 0.07292985663149998, 0.12446171911487247]


15×2 Matrix{Float64}:
 -1.0        -1.0
 -1.0        -1.0
 -1.0        -1.0
 -1.0        -1.0
 -1.0        -1.0
  1.12207     1.12207
  1.10464     1.10464
  0.416993    0.416993
 -0.287588   -0.287588
 -0.229819   -0.229819
  0.421769    0.421769
  1.35559     1.35559
  0.0619374   0.0619374
 -0.703758   -0.703758
 -0.143326   -0.143326

### Bernoulli

In [20]:
# sample data
X = qc_model.data[1].X # d by p
y = qc_model.data[1].y # d by 1

# objective
function resβ(β)
    η = X * β # d by 1
    μ = GLM.linkinv.(LogitLink(), η)
    varμ = GLM.glmvar.(Bernoulli(), μ)
    return (y - μ) ./ sqrt.(varμ) # d by 1
end

# mathematical gradient
function ∇resβ(β::AbstractVector{T}) where T
    d, p = size(X)
    ∇resβ = zeros(T, d, p)
    η = X * β # d by 1
    μ = GLM.linkinv.(LogitLink(), η) # d by 1
    varμ = GLM.glmvar.(Bernoulli(), μ) # d by 1
    res = (y - μ) ./ sqrt.(varμ) # d by 1
    for i in 1:p, j in 1:d
        varμ_j = varμ[j]
        x_ji = X[j, i]
        res_j = res[j]
        μ_j = μ[j]
        ∇resβ[j, i] = -sqrt(varμ_j) * x_ji - 
            (0.5 * res_j * (1 - 2μ_j) * x_ji)
    end
    return ∇resβ # d × p
end
∇²resβ_autodiff = x -> ForwardDiff.jacobian(∇resβ, x)

# autodiff gradient
∇resβ_autodiff = x -> ForwardDiff.jacobian(resβ, x)

# check objective
@show resβ(qc_model.β)

# compare mathematical and numerical gradient
[vec(∇resβ(qc_model.β)) vec(∇resβ_autodiff(qc_model.β))]


resβ(qc_model.β) = [0.5344439504497369, 0.02670454905299698, 0.7098215386604426, 0.44787592964791534, 0.08710902598335912]


15×2 Matrix{Float64}:
 -0.267222   -0.267222
 -0.0133523  -0.0133523
 -0.354911   -0.354911
 -0.223938   -0.223938
 -0.0435545  -0.0435545
  0.554373    0.554373
 -0.025995   -0.025995
  0.0287037   0.0287037
  0.0346223   0.0346223
 -0.0405912  -0.0405912
 -0.604183   -0.604183
 -0.0159986  -0.0159986
  0.0270811   0.0270811
 -0.105382   -0.105382
 -0.0448782  -0.0448782

### Poisson

In [20]:
# sample data
X = qc_model.data[1].X # d by p
y = qc_model.data[1].y # d by 1

# objective
function resβ(β)
    η = X * β # d by 1
    μ = GLM.linkinv.(LogLink(), η)
    varμ = GLM.glmvar.(Poisson(), μ)
    return (y - μ) ./ sqrt.(varμ) # d by 1
end

# mathematical gradient
function ∇resβ(β)
    d, p = size(X)
    ∇resβ = zeros(d, p)
    η = X * β # d by 1
    μ = GLM.linkinv.(LogLink(), η) # d by 1
    varμ = GLM.glmvar.(Poisson(), μ) # d by 1
    res = (y - μ) ./ sqrt.(varμ) # d by 1
    dμ = GLM.mueta.(LogLink(), η) # d by 1
    for i in 1:p, j in 1:d
        varμ_j = varμ[j]
        x_ji = X[j, i]
        res_j = res[j]
        μ_j = μ[j]
        dμ_j = dμ[j]
        ∇resβ[j, i] = x_ji * (-(inv(sqrt(varμ_j)) + (0.5 * inv(varμ_j)) * res_j) * dμ_j)
    end
    return ∇resβ # d × p
end

# autodiff gradient
∇resβ_autodiff = x -> ForwardDiff.jacobian(resβ, x)

# random beta vector
β = rand(size(qc_model.data[1].X, 2))

# check objective
@show resβ(β)

# compare mathematical and numerical gradient
[vec(∇resβ(β)) vec(∇resβ_autodiff(β))]

resβ(β) = [-0.20116605438121704, 654.5724663515489, -0.04513275044062135, 3.5718353780954617, 70.68722761611653]


15×2 Matrix{Float64}:
   -1.73497      -1.73497
 -329.553      -329.553
   -1.00025      -1.00025
   -3.03142      -3.03142
  -37.1641      -37.1641
    3.59933       3.59933
 -641.594      -641.594
    0.0808965     0.0808965
    0.468677      0.468677
  -34.6356      -34.6356
   -3.92273      -3.92273
 -394.867      -394.867
    0.0763233     0.0763233
   -1.42654      -1.42654
  -38.2936      -38.2936

## Check $\nabla_\beta L$

In [192]:
function A_mul_b!(c::AbstractVector{T}, A::AbstractMatrix, b::AbstractVector) where T
    n, p = size(A)
    fill!(c, zero(T))
    for j in 1:p, i in 1:n
        c[i] += A[i, j] * b[j]
    end
    return c
end

function loglikelihood(
    β::AbstractVector{T}, 
    qc_model::Union{GLMCopulaVCModel, NBCopulaVCModel}
    ) where T
    θ = qc_model.θ
    # allocate vector of type T
    n, p = size(qc_model.data[1].X)
    η = zeros(T, n)
    μ = zeros(T, n)
    varμ = zeros(T, n)
    res = zeros(T, n)
    storage_n = zeros(T, n)
    q = zeros(T, length(θ))
    logl = zero(T)
    for (i, gc) in enumerate(qc_model.data)
        X = gc.X
        y = gc.y
        n, p = size(X)
        # update_res! step (need to avoid BLAS)
        A_mul_b!(η, X, β)
        for i in 1:gc.n
            μ[i] = GLM.linkinv(gc.link, η[i])
            varμ[i] = GLM.glmvar(gc.d, μ[i]) # Note: for negative binomial, d.r is used
#             dμ[i] = GLM.mueta(gc.link, η[i])
#             w1[i] = dμ[i] / varμ[i]
#             w2[i] = w1[i] * dμ[i]
            res[i] = y[i] - μ[i]
        end
        # standardize_res! step
        for j in eachindex(y)
            res[j] /= sqrt(varμ[j])
        end
        # std_res_differential! step (this will compute ∇resβ)
#         for i in 1:gc.p
#             for j in 1:gc.n
#                 ∇resβ[j, i] = -sqrt(varμ[j]) * X[j, i] - (0.5 * res[j] * (1 - (2 * μ[j])) * X[j, i])
#             end
#         end
        # update Γ
        @inbounds for k in 1:gc.m
            A_mul_b!(storage_n, gc.V[k], res)
            q[k] = dot(res, storage_n) / 2 # q[k] = 0.5 r' * V[k] * r (update variable b for variance component model)
        end
        # component_loglikelihood
        for j in 1:gc.n
            logl += QuasiCopula.loglik_obs(gc.d, y[j], μ[j], 1.0, 1.0)
        end
        tsum = dot(θ, gc.t)
        logl += -log(1 + tsum)
        qsum  = dot(θ, q) # qsum = 0.5 r'Γr
        logl += log(1 + qsum)
    end
    return logl
end

function loglikelihood(
    β::AbstractVector{T}, 
    gcm::GaussianCopulaVCModel
    ) where T
    θ = gcm.θ
    τ = gcm.τ[1]
    # allocate vector of type T
    n, p = size(gcm.data[1].X)
    μ = zeros(T, n)
    res = zeros(T, n)
    storage_n = zeros(T, n)
    q = zeros(T, length(θ))
    logl = zero(T)
    for gc in gcm.data
        X = gc.X
        y = gc.y
        n, p = size(X)
        sqrtτ = sqrt(abs(τ))
        # update_res! step (need to avoid BLAS)
        A_mul_b!(μ, X, β)
        for i in 1:gc.n
            res[i] = y[i] - μ[i]
        end
        # standardize_res! step
        res .*= sqrtτ
        rss  = abs2(norm(res)) # RSS of standardized residual
        tsum = dot(θ, gc.t) # ben: why is there abs here?
        logl += - log(1 + tsum) - (gc.n * log(2π) -  gc.n * log(abs(τ)) + rss) / 2
        # update Γ
        @inbounds for k in 1:gc.m
            A_mul_b!(storage_n, gc.V[k], res)
            q[k] = dot(res, storage_n) / 2 # q[k] = 0.5 r' * V[k] * r (update variable b for variance component model)
        end
        qsum  = dot(θ, q)
        logl += log(1 + qsum)
    end
    return logl
end

# sample data
autodiff_loglikelihood(β) = loglikelihood(β, qc_model)

# function grad_loglikelihood(
#     β::AbstractVector{T}, 
#     qc_model::Union{GLMCopulaVCModel, NBCopulaVCModel}
#     ) where T
#     β = qc_model.β
#     n, p = size(qc_model.data[1].X)
#     η = zeros(T, n)
#     μ = zeros(T, n)
#     varμ = zeros(T, n)
#     res = zeros(T, n)
#     w1 = zeros(T, n)
#     dμ = zeros(T, n)
#     storage_n = zeros(T, n)
#     out = zeros(length(β))
#     for gc in qc_model.data
#         X = gc.X
#         y = gc.y
#         n, p = size(X)
#         # update_res! step
#         A_mul_b!(η, X, β)
#         for i in 1:gc.n
#             μ[i] = GLM.linkinv(gc.link, η[i])
#             varμ[i] = GLM.glmvar(gc.d, μ[i]) # Note: for negative binomial, d.r is used
#             dμ[i] = GLM.mueta(gc.link, η[i])
#             w1[i] = dμ[i] / varμ[i]
#             res[i] = y[i] - μ[i]
#         end
#         # GLM gradient
#         out += X' * Diagonal(w1) * res
#         # 2nd gradient term
#         res ./= sqrt.(varμ)
        
#     end
#     return out
# end

autodiff_loglikelihood (generic function with 1 method)

In [205]:
autodiff_loglikelihood(qc_model.β), loglikelihood!(qc_model, true, false)

(-8635.392759793393, -8635.39275979312)

Beta is $\pm 5$

In [200]:
# autodiff Gradient
∇logl = x -> ForwardDiff.gradient(autodiff_loglikelihood, x)
∇βtrue = ∇logl(qc_model.β)

3-element Vector{Float64}:
 9.659198719758066e-6
 2.194933313059977e-5
 8.53400730504994e-6

In [201]:
# gradient from math
loglikelihood!(qc_model, true, false)
∇βobs = qc_model.∇β

3-element Vector{Float64}:
 3.149173630434543e-5
 7.270955512718447e-5
 6.383652480647373e-5

Beta is $\pm 2$

In [7]:
# autodiff Gradient
∇logl = x -> ForwardDiff.gradient(autodiff_loglikelihood, x)
∇βtrue = ∇logl(qc_model.β)

3-element Vector{Float64}:
 -2.2863324753430447e-6
 -7.904796714974793e-7
  2.0348114821988617e-6

In [8]:
# gradient from math
loglikelihood!(qc_model, true, false)
∇βobs = qc_model.∇β

3-element Vector{Float64}:
 -2.286331556300425e-6
 -7.904736671893176e-7
  2.0348091102906363e-6

In [13]:
# autodiff Gradient
∇logl = x -> ForwardDiff.gradient(autodiff_loglikelihood, x)
∇βtrue = ∇logl(qc_model.β)

3-element Vector{Float64}:
 -2.2863324753430447e-6
 -7.904796714974793e-7
  2.0348114821988617e-6

In [14]:
# gradient from math
loglikelihood!(qc_model, true, false)
∇βobs = qc_model.∇β

3-element Vector{Float64}:
 -2.286331556300425e-6
 -7.904736671893176e-7
  2.0348091102906363e-6

In [ ]:
# my naive gradient (does not work)
# function compute_∇resβ(β, X, y, dist, link)
#     d, p = size(X)
#     ∇resβ = zeros(d, p)
#     η = X * β # d by 1
#     μ = GLM.linkinv.(link, η) # d by 1
#     varμ = GLM.glmvar.(dist, μ) # d by 1
#     res = (y - μ) ./ sqrt.(varμ) # d by 1
#     for i in 1:p, j in 1:d
#         varμ_j = varμ[j]
#         x_ji = X[j, i]
#         res_j = res[j]
#         μ_j = μ[j]
#         ∇resβ[j, i] = -sqrt(varμ_j) * x_ji - 
#             (0.5 * res_j * (1 - 2μ_j) * x_ji)
#     end
#     return ∇resβ # d × p
# end
# function grad_logl_sample_i(dist, link, Γ, X, y, β)
#     η = X*β
#     μ = GLM.linkinv.(link, η)
#     varμ = GLM.glmvar.(dist, μ)
#     res = (y .- μ) ./ sqrt.(varμ)
#     denom = 1 + 0.5 * (res' * Γ * res)
#     ∇resβ = compute_∇resβ(β, X, y, dist, link)
#     W1 = GLM.mueta.(link, η) / GLM.glmvar.(dist, μ)
#     return X' * Diagonal(W1) * (y - μ) + ∇resβ'*Γ*res / denom
# end

# ∇β_test = zeros(3)
# for i in 1:length(qc_model.data)
#     Γ = sum(qc_model.θ .* qc_model.data[i].V)
#     X = qc_model.data[i].X
#     y = qc_model.data[i].y
#     ∇β_test += grad_logl_sample_i(Bernoulli(), LogitLink(), Γ, X, y, qc_model.β)
# end
# ∇β_test

In [14]:
# autodiff Gradient
∇logl = x -> ForwardDiff.gradient(autodiff_loglikelihood, x)
∇βtrue = ∇logl(qc_model.β)

3-element Vector{Float64}:
  8.57327120407092e-8
  2.7007899694453386e-8
 -1.1578850189764012e-7

In [15]:
# gradient from math
loglikelihood!(qc_model, true, false)
∇βobs = qc_model.∇β

3-element Vector{Float64}:
  8.528801986873447e-8
  2.6077807413482645e-8
 -1.1694493039574039e-7

## Check $\nabla_\beta^2 L$

Hessians for a single observation seems to differ quite a bit

In [28]:
function two_term_Hessian(gcm::Union{GLMCopulaVCModel, NBCopulaVCModel})
    p = length(gcm.β)
    T = eltype(gcm.β)
    H = zeros(T, p, p)
    for gc in gcm.data
        d = gc.n # number of observations for current sample
        # GLM term
        H -= Transpose(gc.X) * Diagonal(gc.w2) * gc.X
        # trailing terms
        res = gc.res # d × 1 standardized residuals
        ∇resβ = gc.∇resβ # d × p
        Γ = zeros(T, d, d)
        for k in 1:gc.m # loop over variance components
            Γ .+= gcm.θ[k] .* gc.V[k]
        end
        denom = abs2(1 + 0.5 * (res' * Γ * res))
        H -= (∇resβ' * Γ * res) * (∇resβ' * Γ * res)' / denom
    end
    return H
end

function two_term_Hessian(gcm::GaussianCopulaVCModel)
    p = length(gcm.β)
    T = eltype(gcm.β)
    H = zeros(T, p, p)
    for gc in gcm.data
        d = gc.n # number of observations for current sample
        # GLM term
        H -= Transpose(gc.X) * gc.X
        # trailing terms
        res = gc.res # d × 1 standardized residuals
        ∇resβ = -sqrt(gcm.τ[1]) .* gc.X # d × p
        Γ = zeros(T, d, d)
        for k in 1:gc.m # loop over variance components
            Γ .+= gcm.θ[k] .* gc.V[k]
        end
        denom = abs2(1 + 0.5 * (res' * Γ * res))
        H -= (∇resβ' * Γ * res) * (∇resβ' * Γ * res)' / denom
    end
    return H
end

function three_term_hessian(qc_model::Union{GLMCopulaVCModel, NBCopulaVCModel})
#     # sarah's implementation
#     loglikelihood!(qc_model, true, true)
#     return qc_model.Hβ
#     @show qc_model.Hβ
    p = length(qc_model.β)
    T = eltype(qc_model.β)
    H = zeros(T, p, p)
    for gc in qc_model.data
        d = gc.n # number of observations for current sample
        # GLM term
        H -= Transpose(gc.X) * Diagonal(gc.w2) * gc.X
        # 2nd term
        res = gc.res # d × 1 standardized residuals
        ∇resβ = gc.∇resβ # d × p
        Γ = zeros(T, d, d)
        for k in 1:gc.m # loop over variance components
            Γ .+= qc_model.θ[k] .* gc.V[k]
        end
        denom = 1 + 0.5 * (res' * Γ * res)
        H -= (∇resβ' * Γ * res) * (∇resβ' * Γ * res)' / denom^2
        # 3rd term
        H += (∇resβ' * Γ * ∇resβ) / denom
    end
    return H
end

# autodiff ∇²resβ (giving some kind of tensor)
∇²resβ_autodiff = x -> ForwardDiff.jacobian(∇resβ, x)

# this is d²rᵢₖ(β) needed for computing the 4th hessian term
function r_ik(β, k)
    res = resβ(β)
    return res[k]
end
r_ik(β) = r_ik(β, k)
∇²r_ik = x -> ForwardDiff.hessian(r_ik, x)

function full_hessian(qc_model::Union{GLMCopulaVCModel, NBCopulaVCModel})
    p = length(qc_model.β)
    T = eltype(qc_model.β)
    H = zeros(T, p, p)    
    # loop over samples
    for (i, gc) in enumerate(qc_model.data)
        d = gc.n # number of observations for current sample
        # GLM term
        H -= Transpose(gc.X) * Diagonal(gc.w2) * gc.X
        # 2nd term
        res = gc.res # d × 1 standardized residuals
        ∇resβ = gc.∇resβ # d × p
        Γ = zeros(T, d, d)
        for k in 1:gc.m # loop over variance components
            Γ .+= qc_model.θ[k] .* gc.V[k]
        end
        denom = 1 + 0.5 * (res' * Γ * res)
        H -= (∇resβ' * Γ * res) * (∇resβ' * Γ * res)' / denom^2
        # 3rd term
        H += (∇resβ' * Γ * ∇resβ) / denom
        # 4th term
        ek = zeros(d)    
        for k in 1:d
            # somehow need to define autodiff functions here, or else k is treated as fixed
            function resβ(β)
                η = X * β # d by 1
                μ = GLM.linkinv.(LogitLink(), η)
                varμ = GLM.glmvar.(Bernoulli(), μ)
                return (y - μ) ./ sqrt.(varμ) # d by 1
            end
            r_ik(β, k) = resβ(β)[k]
            r_ik(β) = r_ik(β, k)
            ∇²r_ik = x -> ForwardDiff.hessian(r_ik, x) 
            
            
            fill!(ek, 0)
            ek[k] = 1
            X = gc.X
            y = gc.y
#             @show ∇²r_ik(qc_model.β)
            H += (ek' * Γ * res * ∇²r_ik(qc_model.β)) / denom
        end
    end
    return H
end

full_hessian (generic function with 1 method)

In [29]:
# directly evaluating ∇²resβ (giving some kind of tensor)
Hββ = ∇²resβ_autodiff(qc_model.β)

15×3 Matrix{Float64}:
 -0.253406    0.525711    -0.572947
 -0.279741   -0.544617    -0.335183
 -0.263081    0.0212769    0.0200741
 -0.263562    0.0407485   -0.124028
 -0.272238   -0.253716    -0.280512
  0.525711   -1.09063      1.18862
 -0.544617   -1.06029     -0.652555
  0.0212769  -0.00172079  -0.00162351
  0.0407485  -0.00629998   0.0191756
 -0.253716   -0.236454    -0.261427
 -0.572947    1.18862     -1.29542
 -0.335183   -0.652555    -0.401613
  0.0200741  -0.00162351  -0.00153173
 -0.124028    0.0191756   -0.0583658
 -0.280512   -0.261427    -0.289037

In [30]:
# calculating hessian of r_ik for k = 1:p
k = 1
∇²r_ik(qc_model.β)

3×3 Matrix{Float64}:
 -0.253406   0.525711  -0.572947
  0.525711  -1.09063    1.18862
 -0.572947   1.18862   -1.29542

In [31]:
# calculating hessian of r_ik for k = 1:p
k = 2
∇²r_ik(qc_model.β)

3×3 Matrix{Float64}:
 -0.279741  -0.544617  -0.335183
 -0.544617  -1.06029   -0.652555
 -0.335183  -0.652555  -0.401613

In [33]:
# 2 term Hessian from math
two_terms_H = two_term_Hessian(qc_model)

3×3 Matrix{Float64}:
 -5800.35       28.5649     84.1043
    28.5649  -5155.84       59.5103
    84.1043     59.5103  -5164.75

In [34]:
# 3 term Hessian from math
three_term_hessian(qc_model)

3×3 Matrix{Float64}:
 -3684.56       28.4691     61.3107
    28.4691  -4268.18       48.266
    61.3107     48.266   -4284.97

In [35]:
# 3 term Hessian implemented by sarah
loglikelihood!(qc_model, true, true)
qc_model.Hβ

3×3 Matrix{Float64}:
 -3684.56       28.4691     61.3107
    28.4691  -4268.18       48.266
    61.3107     48.266   -4284.97

In [36]:
# 4 term Hessian from math
full_hessian(qc_model)

3×3 Matrix{Float64}:
 -2793.55       27.4235     44.8972
    27.4235  -3385.69       43.6875
    44.8972     43.6875  -3393.24

In [39]:
# autodiff Hessian
∇²logl = x -> ForwardDiff.hessian(
        autodiff_loglikelihood, x)
autodiff_H = ∇²logl(qc_model.β)

3×3 Matrix{Float64}:
 -2793.55       27.4235     44.8972
    27.4235  -3385.69       43.6875
    44.8972     43.6875  -3393.24

# Check $\nabla_{\theta}L$, $\nabla^2_{\theta}L$, and $\nabla_{\theta}\nabla_{\beta} L$ 

In [11]:
# Loglikelihood function friendly to autodiff
autodiff_loglikelihood(β) = QuasiCopula.loglikelihood(β, qc_model, z)

# autodiff Gradient
∇logl = x -> ForwardDiff.gradient(autodiff_loglikelihood, x)

# autodiff Hessian
∇²logl = x -> ForwardDiff.hessian(autodiff_loglikelihood, x)


#22 (generic function with 1 method)

First, check if `autodiff_loglikelihood` returns same answer as `QuasiCopula.loglikelihood!`

In [16]:
i = 1
z = convert(Vector{Float64}, @view(G[:, i]), center=true, scale=false)
fullβ = [qc_model.β; qc_model.θ; 0.0] # poisson or bernoulli
# fullβ = [qc_model.β; qc_model.θ; qc_model.τ; 0.0] # normal

@show autodiff_loglikelihood(fullβ)
@show QuasiCopula.loglikelihood!(qc_model, false, false);

autodiff_loglikelihood(fullβ) = -18033.163626812184
QuasiCopula.loglikelihood!(qc_model, false, false) = -18033.16362681217


### Check $\nabla_\theta L$

In [39]:
# autodiff (the 4th and 5th position stores the 2 gradient terms with respect to θ)
i = 5
z = convert(Vector{Float64}, @view(G[:, i]), center=true, scale=false)
fullβ = [qc_model.β; qc_model.θ; 0.0] # poisson or bernoulli
∇logl(fullβ)[4:5]

2-element Vector{Float64}:
 -1.1370986533992892e-6
  2.3139215938341664e-6

In [40]:
# mathematical formula
Ω = qc_model.data[i].V
m = length(Ω)
grad_math = zeros(m)
for i in 1:length(qc_model.data)
    r = qc_model.data[i].res
    Ω = qc_model.data[i].V
    b = [0.5r' * Ω[k] * r for k in 1:m]
    c = [0.5tr(Ω[k]) for k in 1:m]
    grad_math += b / (1 + qc_model.θ'*b) - c / (1 + qc_model.θ'*c)
end
grad_math

2-element Vector{Float64}:
 -1.137098653399271e-6
  2.3139215938342303e-6

### Check $\nabla_\theta^2 L$

In [37]:
# autodiff (the 4th and 5th position stores the 2 gradient terms with respect to θ)
i = 5
z = convert(Vector{Float64}, @view(G[:, i]), center=true, scale=false)
fullβ = [qc_model.β; qc_model.θ; 0.0] # poisson or bernoulli
∇²logl(fullβ)[4:5, 4:5]


2×2 Matrix{Float64}:
 1.25985e-15   1.0245e-15
 1.0245e-15   -9.38656e-15

In [62]:
# mathematical formula
Ω = qc_model.data[i].V
m = length(Ω)
hess_math = zeros(m, m)
for i in 1:length(qc_model.data)
    r = qc_model.data[i].res
    Ω = qc_model.data[i].V
    b = [0.5r' * Ω[k] * r for k in 1:m]
    c = [0.5tr(Ω[k]) for k in 1:m]
    hess_math += b*b' / (1 + qc_model.θ'*b)^2 - c*c' / (1 + qc_model.θ'*c)^2
end
hess_math

2×2 Matrix{Float64}:
 -1.25985e-15  -1.0245e-15
 -1.0245e-15    9.38656e-15

### Check $\nabla_\theta\nabla_\beta L$

In [44]:
# autodiff (the 4th and 5th position stores the 2 gradient terms with respect to θ)
i = 5
z = convert(Vector{Float64}, @view(G[:, i]), center=true, scale=false)
fullβ = [qc_model.β; qc_model.θ; 0.0] # poisson or bernoulli
∇²logl(fullβ)[1:3, 4:5]

3×2 Matrix{Float64}:
 -1.0073e-7   2.04979e-7
 -4.43245e-8  9.01974e-8
 -5.11492e-8  1.04085e-7

In [68]:
# mathematical formula
Ω = qc_model.data[i].V
m = length(Ω)
p = size(qc_model.data[i].X, 2)
hess_math = zeros(p, m)
for i in 1:length(qc_model.data)
    r = qc_model.data[i].res
    Ω = qc_model.data[i].V
    θ = qc_model.θ
    ∇resβ = qc_model.data[i].∇resβ
    b = [0.5r' * Ω[k] * r for k in 1:m]
    A = hcat([∇resβ' * Ω[k] * r for k in 1:m]...)
    hess_math += A ./ (1 + θ'*b) - (A*θ ./ (1 + θ'*b)^2) * b'
end
hess_math

3×2 Matrix{Float64}:
 -1.0073e-7   2.04979e-7
 -4.43245e-8  9.01974e-8
 -5.11492e-8  1.04085e-7

## Check $\frac{\partial^2\mu}{\partial \eta^2}$

In [73]:
"""
    mueta2(l::Link, η::Real)

Second derivative of the inverse link function `d^2μ/dη^2`, for link `L` at linear predictor value `η`.
I.e. derivative of the mueta function in GLM.jl
"""
function mueta2 end

mueta2(::IdentityLink, η::Real) = zero(η)
function mueta2(::LogitLink, η::Real)
    expabs = exp(-abs(η))
    denom = 1 + expabs
    return -expabs / denom^2 + 2expabs^2 / denom^3
end
mueta2(::LogLink, η::Real) = exp(η)

mueta2 (generic function with 3 methods)

In [74]:
# test mueta2 function
# l = IdentityLink()
# l = LogLink()
l = LogitLink()
η = 0.1234
μ = GLM.linkinv(l, η)

# mathematical hessian
@show mueta2(l, η)

# ForwardDiff Hessian
logit_mueta = η -> GLM.mueta(l, η)
mueta2_autodiff = x -> ForwardDiff.derivative(logit_mueta, x)
@show mueta2_autodiff(η);

mueta2(l, η) = -0.015346957645411913
mueta2_autodiff(η) = -0.015346957645411843


## Check $\frac{\partial\sigma^2}{\partial \mu}$

In [75]:
"""
    sigmaeta(D::Distribution, μ::Real)

Computes dσ²/dμ
"""
function sigmamu end

sigmamu(::Normal, μ::Real) = zero(μ)
sigmamu(::Bernoulli, μ::Real) = one(μ) - 2μ
sigmamu(::Poisson, μ::Real) = one(μ)

sigmamu (generic function with 3 methods)

## Check $\frac{\partial^2(\sigma^2)}{\partial \mu^2}$

In [76]:
"""
    sigmaμ2(D::Distribution, μ::Real)

Computes d²σ²/dμ²
"""
function sigmamu2 end

sigmamu2(::Normal, μ::Real) = zero(μ)
sigmamu2(::Bernoulli, μ::Real) = -2
sigmamu2(::Poisson, μ::Real) = zero(μ)

sigmamu2 (generic function with 3 methods)

## Check $\nabla \mu$, $\nabla^2 \mu$, $\nabla \sigma^2$ and $\nabla^2 \sigma^2$

In [77]:
"""
    ∇²μ_j(l::Link, Xi::Matrix, β::Vector, j)

Computes the Hessian of the mean function with respect to β for sample i (Xi) at time j
"""
function ∇²μ_j(l::Link, Xi::Matrix, β::Vector, j)
    xj = Xi[j, :]
    ηj = dot(xj, β)
    d²μdη² = mueta2(l, ηj)
    return d²μdη² * xj * xj'
end

# objective 
function eval_μj(X, β, link, j)
    η = X*β
    μj = GLM.linkinv(link, η[j])
    return μj
end

# autodiff hessian
eval_μj(β) = eval_μj(X, β, link, j)
∇²μ_j_autodiff = x -> ForwardDiff.hessian(eval_μj, x)

# data
link = LogitLink()
X = qc_model.data[1].X
β = qc_model.β
j = 1
@show eval_μj(X, β, link, j)

# compare autodiff and mathematical result
math_result = ∇²μ_j(link, X, β, j)
autodiff_result = ∇²μ_j_autodiff(β)

[vec(math_result) vec(autodiff_result)]

eval_μj(X, β, link, j) = 0.5614464525554457


9×2 Matrix{Float64}:
 -0.0302592   -0.0302592
  0.033953     0.033953
  0.0127624    0.0127624
  0.033953     0.033953
 -0.0380978   -0.0380978
 -0.0143203   -0.0143203
  0.0127624    0.0127624
 -0.0143203   -0.0143203
 -0.00538278  -0.00538278

In [78]:
"""
    ∇²σ²_j(d::Distribution, l::Link, Xi::Matrix, β::Vector, j)

Computes the Hessian of the σ^2 function with respect to β for sample i (Xi) at time j
"""
function ∇²σ²_j(d::Distribution, l::Link, Xi::Matrix, β::Vector, j)
    xj = Xi[j, :]
    ηj = dot(xj, β)
    μj = GLM.linkinv.(l, ηj)
    c = sigmamu2(d, μj)*GLM.mueta(l, ηj)^2 + sigmamu(d, μj)*mueta2(l, ηj)
    return c * xj * xj'
end

# objective
function eval_σ2j(X, β, dist, link, j)
    η = X*β
    μ = GLM.linkinv.(link, η)
    σ2j = GLM.glmvar(dist, μ[j])
    return σ2j
end

# autodiff hessian
eval_σ2j(β) = eval_σ2j(X, β, dist, link, j)
∇²σ2j_autodiff = x -> ForwardDiff.hessian(eval_σ2j, x)

# data
dist = Bernoulli()
link = LogitLink()
X = qc_model.data[1].X
β = qc_model.β
j = 1
@show eval_σ2j(X, β, dist, link, j)

# compare autodiff and mathematical result
math_result = ∇²σ²_j(dist, link, X, β, j)
autodiff_result = ∇²σ2j_autodiff(β)

[vec(math_result) vec(autodiff_result)]

eval_σ2j(X, β, dist, link, j) = 0.24622433346835138


9×2 Matrix{Float64}:
 -0.117534   -0.117534
  0.131882    0.131882
  0.0495722   0.0495722
  0.131882    0.131882
 -0.147981   -0.147981
 -0.0556237  -0.0556237
  0.0495722   0.0495722
 -0.0556237  -0.0556237
 -0.020908   -0.020908

## Show that we can compute $∇resβ$ generally, although we don't do so in practice

In [90]:
# sample data
X = qc_model.data[1].X # d by p
y = qc_model.data[1].y # d by 1

# objective
function resβ(X, y, β)
    η = X * β # d by 1
    μ = GLM.linkinv.(LogitLink(), η)
    varμ = GLM.glmvar.(Bernoulli(), μ)
    return (y - μ) ./ sqrt.(varμ) # d by 1
end
resβ(β) = resβ(X, y, β)

# mathematical gradient
function ∇resβ(X, y, β::AbstractVector{T}) where T
    dist = Bernoulli()
    link = LogitLink()
    
    d, p = size(X)
    ∇resβ = zeros(T, d, p)
    η = X * β # d by 1
    μ = GLM.linkinv.(link, η) # d by 1
    varμ = GLM.glmvar.(dist, μ) # d by 1
    res = (y - μ) ./ sqrt.(varμ) # d by 1
    dμ = GLM.mueta.(link, η) # d by 1
    for i in 1:p, j in 1:d
        varμ_j = varμ[j]
        x_ji = X[j, i]
        res_j = res[j]
        μ_j = μ[j]
        dμ_j = dμ[j]
        dμdβ = dμ_j * x_ji
        dσ2dβ = sigmamu(dist, μ_j) * dμdβ
        # in practice, we have update_∇resβ fucntions to compute ∇resβ[j, i]
        ∇resβ[j, i] = -inv(sqrt(varμ_j)) * dμdβ - 0.5 * res_j * inv(varμ_j) * dσ2dβ
    end
    return ∇resβ # d × p
end
∇resβ(β) = ∇resβ(X, y, β)
∇²resβ_autodiff = x -> ForwardDiff.jacobian(∇resβ, x)

# autodiff gradient
∇resβ_autodiff = x -> ForwardDiff.jacobian(resβ, x)

# compare mathematical and numerical gradient
[vec(∇resβ(qc_model.β)) vec(∇resβ_autodiff(qc_model.β))]

15×2 Matrix{Float64}:
 -0.565735   -0.565735
 -0.449521   -0.449521
 -0.736097   -0.736097
 -0.23579    -0.23579
 -0.27525    -0.27525
  0.634795    0.634795
  0.496558    0.496558
  0.306947    0.306947
 -0.0678103  -0.0678103
 -0.0632576  -0.0632576
  0.238609    0.238609
  0.609367    0.609367
  0.045592    0.045592
 -0.165939   -0.165939
 -0.0394505  -0.0394505

## Compute $∇^2resβ$: Hessian of residual vector of sample $i$ at observation $k$

In [145]:
# mathematical Hessian of residuals wrt β for sample i at time j
# note: need function sigmamu, sigmamu2, mueta2
function ∇²resβ_ij(qc_model, i, j)
    dist = Bernoulli()
    link = LogitLink()
    
    X = qc_model.data[i].X
    y = qc_model.data[i].y
    β = qc_model.β
    xj = X[j, :]
    d, p = size(X)
    
    # intermediate quantities?
    η = X * β # d by 1
    μ = GLM.linkinv.(link, η) # d by 1
    varμ = GLM.glmvar.(dist, μ) # d by 1
    res = (y - μ) ./ sqrt.(varμ) # d by 1
    invσ = inv.(sqrt.(varμ))
    ∇μ_ij  = GLM.mueta(link, η[j]) * xj
    ∇σ²_ij = sigmamu(dist, μ[j]) * GLM.mueta(link, η[j]) * xj

    # assemble 5 terms
    term1 = -invσ[j] * ∇²μ_j(link, X, β, j)
    term2 = 0.5invσ[j]^3 * ∇σ²_ij * ∇μ_ij'
    term3 = -0.5 * res[j] * inv(varμ[j]) * ∇²σ²_j(dist, link, X, β, j)
    term4 = 0.5invσ[j]^3 * ∇μ_ij * ∇σ²_ij'
    term5 = 0.75res[j] * inv(varμ[j]^2) * ∇σ²_ij * ∇σ²_ij'
    ∇²resβ_ik = term1 + term2 + term3 + term4 + term5

    return ∇²resβ_ik # p × p
end
i = 1 # sample id
j = 1 # time point
∇²resβ_ij(qc_model, 1, 1)

3×3 Matrix{Float64}:
 -0.282867   0.317398   0.119305
  0.317398  -0.356143  -0.133868
  0.119305  -0.133868  -0.0503189

In [146]:
# autodiff Hessian of residuals wrt β for sample i at time j
β = qc_model.β
# gc = qc_model.data[1]
T = eltype(β)
X = qc_model.data[i].X
y = qc_model.data[i].y

p = length(β)
d = qc_model.data[i].n
H = zeros(T, p, p)
ek = zeros(T, d)
k = 1

function resβ(X, y, β)
    η = X * β # d by 1
    μ = GLM.linkinv.(LogitLink(), η)
    varμ = GLM.glmvar.(Bernoulli(), μ)
    return (y - μ) ./ sqrt.(varμ) # d by 1
end
r_ik(β, k) = resβ(X, y, β)[k]
r_ik(β) = r_ik(β, k)
∇²r_ik = x -> ForwardDiff.hessian(r_ik, x) 
∇²r_ik(β)


3×3 Matrix{Float64}:
 -0.282867   0.317398   0.119305
  0.317398  -0.356143  -0.133868
  0.119305  -0.133868  -0.0503189

## Compute $d_\gamma d_\gamma  r_{ik}$: Hessian of residual vector of sample $i$ at observation $j$

Because $\gamma$ is a scalar, the resulting Hessian is a vector with length of $\beta$. 

In [125]:
# # math (note: this is same as dβdβ_res_ij but we just plug in z in place of xj)
# function dγdγ_res_ij(dist, link, xj, η_j, μ_j, varμ_j, res_j)
#     invσ_j = inv(sqrt(varμ_j))
#     ∇μ_ij  = GLM.mueta(link, η_j) * xj
#     ∇σ²_ij = sigmamu(dist, μ_j) * GLM.mueta(link, η_j) * xj

#     # assemble 5 terms
#     term1 = -invσ_j * QuasiCopula.∇²μ_j(link, η_j, xj)
#     term2 = 0.5invσ_j^3 * ∇σ²_ij * ∇μ_ij'
#     term3 = -0.5 * res_j * inv(varμ_j) * QuasiCopula.∇²σ²_j(dist, link, xj, μ_j, η_j)
#     term4 = 0.5invσ_j^3 * ∇μ_ij * ∇σ²_ij'
#     term5 = 0.75res_j * inv(varμ_j^2) * ∇σ²_ij * ∇σ²_ij'
#     result = term1 + term2 + term3 + term4 + term5

#     return result # 1 × 1
# end
# z = rand()
# η_j = rand()
# μ_j = rand()
# varμ_j = rand()
# res_j = rand()
# dγdγ_res_ij(Bernoulli(), LogitLink(), z, η_j, μ_j, varμ_j, res_j)

-0.09308160081535394

In [139]:
# # autodiff
# function r_j(y, X, z, β, γ, j)
#     η = X * β + z * γ
#     μ = GLM.linkinv.(LogitLink(), η)
#     varμ = GLM.glmvar.(Bernoulli(), μ)
#     res = (y - μ) ./ sqrt.(varμ)
#     return res[j]
# end
# r_j(γ) = r_j(y, X, z, β, γ, j)
# auto_dγdγ_res_ij = x -> ForwardDiff.hessian(r_j, x) 

# γ = rand()
# z = rand(5)
# r_j(γ)
# auto_dγdγ_res_ij([γ])

LoadError: MethodError: no method matching *(::Vector{Float64}, ::Vector{ForwardDiff.Dual{ForwardDiff.Tag{typeof(r_j), Float64}, ForwardDiff.Dual{ForwardDiff.Tag{typeof(r_j), Float64}, Float64, 1}, 1}})
Closest candidates are:
  *(::Any, ::Any, ::Any, ::Any...) at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/base/operators.jl:655
  *(::StridedMatrix{T}, ::StridedVector{S}) where {T<:Union{Float32, Float64, ComplexF32, ComplexF64}, S<:Real} at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/LinearAlgebra/src/matmul.jl:44
  *(::StridedVecOrMat, ::Adjoint{<:Any, <:LinearAlgebra.LQPackedQ}) at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/LinearAlgebra/src/lq.jl:266
  ...

## Check Q term

When $\beta$ have large effects, the Hessian with respect to beta no longer match autodiff. Lets try to reproduce this behavior

+ $Q = d_{\gamma}^2 \mathcal{L}$ is the Hessian of the loglikelihood with respect to the effect of the SNP $\gamma$. 

In [31]:

function loglikelihood_i(
    par::AbstractVector{T}, # p+m+1 × 1 where m is number of VCs, 1 is for the SNP
    qc_model::Union{GLMCopulaVCModel, NBCopulaVCModel}, # fitted null model
    z::AbstractVector, # n × 1 genotype vector
    i::Int # sample log
    ) where T
    p = qc_model.p
    m = length(par) - 1 - p
    β = [par[1:end-(m+1)]; par[end]] # nongenetic + genetic beta
    θ = par[end-m:end-1]             # vc parameters
    # allocate storage vectors of type T
    nmax = maximum(size(qc_model.data[i].X, 1) for i in 1:length(qc_model.data))
    η_store = zeros(T, nmax)
    μ_store = zeros(T, nmax)
    varμ_store = zeros(T, nmax)
    res_store = zeros(T, nmax)
    storage_n_store = zeros(T, nmax)
    Xstore = zeros(T, nmax, p+1)
    q = zeros(T, length(θ))
    logl = zero(T)
        
    gc = qc_model.data[i]
        n = size(gc.X, 1)
        X = @view(Xstore[1:n, :])
        η = @view(η_store[1:n])
        μ = @view(μ_store[1:n])
        varμ = @view(varμ_store[1:n])
        res = @view(res_store[1:n])
        storage_n = @view(storage_n_store[1:n])
        # sync nogenetic + genetic covariates
        copyto!(X, gc.X)
        X[:, end] .= z[i]
        y = gc.y
        # update_res! step (need to avoid BLAS)
        QuasiCopula.A_mul_b!(η, X, β)
        for j in 1:gc.n
            μ[j] = GLM.linkinv(gc.link, η[j])
            varμ[j] = GLM.glmvar(gc.d, μ[j]) # Note: for negative binomial, d.r is used
            # dμ[j] = GLM.mueta(gc.link, η[j])
            # w1[j] = dμ[j] / varμ[j]
            # w2[j] = w1[j] * dμ[j]
            res[j] = y[j] - μ[j]
        end
        # standardize_res! step
        for j in eachindex(y)
            res[j] /= sqrt(varμ[j])
        end
        # std_res_differential! step (this will compute ∇resβ)
        # for i in 1:gc.p
        #     for j in 1:gc.n
        #         ∇resβ[j, i] = -sqrt(varμ[j]) * X[j, i] - (0.5 * res[j] * (1 - (2 * μ[j])) * X[j, i])
        #     end
        # end
        # update Γ
        @inbounds for k in 1:gc.m
            QuasiCopula.A_mul_b!(storage_n, gc.V[k], res)
            q[k] = dot(res, storage_n) / 2 # q[k] = 0.5 r' * V[k] * r (update variable b for variance component model)
        end
        # component_loglikelihood
        for j in 1:gc.n
            logl += QuasiCopula.loglik_obs(gc.d, y[j], μ[j], one(T), one(T))
        end
        tsum = dot(θ, gc.t)
        logl += -log(1 + tsum)
        qsum  = dot(θ, q) # qsum = 0.5 r'Γr
        logl += log(1 + qsum)
#     end
    return logl
end

loglikelihood_i (generic function with 1 method)

In [109]:
function calculate_Qi(qc_model, gc::GLMCopulaVCObs, z, Γ, i)
    β = qc_model.β
    X = gc.X
    y = gc.y
    
        dist = gc.d
        d = gc.n # number of observations for current sample
        # the snp
        zi = fill(z[i], gc.n)
        # update ∇resγ
        ∇resγ = zeros(d)
        ∇resβ = gc.∇resβ # d × p
        res = gc.res # d × 1 standardized residuals
        for k in 1:d # loop over each sample's observation
            ∇resγ[k] = QuasiCopula.update_∇resβ(dist, zi[k], res[k], gc.μ[k], gc.dμ[k], gc.varμ[k])
        end
        denom = 1 + 0.5 * (res' * Γ * res)
        denom2 = abs2(denom)
    
    #
    # check dβdβ_res_ij for γ term matches autodiff
    #
    # autodiff
    auto_resβ_ij = Float64[]
    for k in 1:d
        # somehow this has to be inside the loop in order to vary the `k` parameter
        function resγ(X, y, β, z, γ)
            η = X * β + z .* γ # d by 1: z is vector of size == size(X, 1)
            μ = GLM.linkinv.(LogitLink(), η)
            varμ = GLM.glmvar.(Bernoulli(), μ)
            return (y - μ) ./ sqrt.(varμ) # d by 1
        end
        res_ik(γ, k) = resγ(X, y, β, zi, γ)[k] # residual of sample i at measurement k
        res_ik(γ) = res_ik(γ, k) 
        auto_dβdβ_res_ij = x -> ForwardDiff.hessian(res_ik, x) 
        # evaluate autodiff
        push!(auto_resβ_ij, auto_dβdβ_res_ij([0.0])[1])
    end
    @show auto_resβ_ij
    # math 
    math_resβ_ij = Float64[]
    for k in 1:d
        push!(math_resβ_ij, QuasiCopula.dβdβ_res_ij(gc.d, gc.link, z[i], gc.η[k], gc.μ[k], gc.varμ[k], res[k]))
    end
    @show math_resβ_ij
    fdsa
            
    Q = 0.0
    Q += Transpose(zi) * Diagonal(gc.w2) * zi
    Q += (∇resγ' * Γ * res) * (∇resγ' * Γ * res)' / denom2 # 2nd term
    Q -= ∇resγ' * Γ * ∇resγ / denom # 3rd term
    ek = zeros(d)
    for k in 1:d
        fill!(ek, 0)
        ek[k] = 1
        Q -= (ek' * Γ * res * QuasiCopula.dβdβ_res_ij(gc.d, gc.link, z[i], gc.η[k], gc.μ[k], gc.varμ[k], res[k])) / denom
        Q -= numer
    end
    return Q
end

calculate_Qi (generic function with 3 methods)

When $i = 1$ and $k = 2$, dβdβ_res_ij fails to match autodiff, why??

In [127]:
i = 1
k = 1
gc = qc_model.data[i]
y = gc.y
X = gc.X
z = fill(z[i], size(X, 1))
γ = [0.0]

# autodiff
function resγ(X, y, β, z, γ)
    η = X * β + z .* γ # d by 1: z is vector of size == size(X, 1)
    μ = GLM.linkinv.(LogitLink(), η)
    varμ = GLM.glmvar.(Bernoulli(), μ)
    return (y - μ) ./ sqrt.(varμ) # d by 1
end
res_ik(γ, k) = resγ(X, y, β, zi, γ)[k] # residual of sample i at measurement k
res_ik(γ) = res_ik(γ, k) 
auto_dβdβ_res_ij = x -> ForwardDiff.hessian(res_ik, x)
auto = auto_dβdβ_res_ij(γ)[1]
@show auto

# math
math = QuasiCopula.dβdβ_res_ij(gc.d, gc.link, z[i], gc.η[k], gc.μ[k], gc.varμ[k], gc.res[k])
@show math;

auto = -0.09693671578820441
η_j = 0.24703448524051816
GLM.mueta(link, η_j) = 0.24622433346835135
varμ_j = 0.24622433346835138
invσ_j = 2.0152759158475693
∇μ_ij = -0.1441397248123729
∇σ²_ij = 0.017713749524076932
term1 = 0.020897663522326825
term2 = -0.010448831761163407
term3 = -0.09254470722633086
term4 = -0.010448831761163409
term5 = -0.00439200856187351
math = -0.09693671578820436


In [128]:
i = 1
k = 2
gc = qc_model.data[i]
y = gc.y
X = gc.X
z = fill(z[i], size(X, 1))
γ = [0.0]

# autodiff
function resγ(X, y, β, z, γ)
    η = X * β + z .* γ # d by 1: z is vector of size == size(X, 1)
    μ = GLM.linkinv.(LogitLink(), η)
    varμ = GLM.glmvar.(Bernoulli(), μ)
    return (y - μ) ./ sqrt.(varμ) # d by 1
end
res_ik(γ, k) = resγ(X, y, β, zi, γ)[k] # residual of sample i at measurement k
res_ik(γ) = res_ik(γ, k) 
auto_dβdβ_res_ij = x -> ForwardDiff.hessian(res_ik, x)
auto = auto_dβdβ_res_ij(γ)[1]
@show auto

# math
math = QuasiCopula.dβdβ_res_ij(gc.d, gc.link, z[i], gc.η[k], gc.μ[k], gc.varμ[k], gc.res[k])
@show math;

auto = -0.07702396925952908
η_j = -0.21284889183092182
GLM.mueta(link, η_j) = 0.24718970323767067
varμ_j = 0.2471897032376707
invσ_j = 2.011336856888617
∇μ_ij = -0.14470485227533242
∇σ²_ij = -0.015342254457215551
term1 = 0.01806453186341636
term2 = 0.009032265931708191
term3 = -0.07788981010525632
term4 = 0.009032265931708191
term5 = -0.0025975225371817007
math = -0.04435826891560527


In [129]:
# get snp 1
snp = 1
z = convert(Vector{Float64}, @view(G[:, snp]), center=true)

# mathematical Q
math_Q = 0.0
for i in 1:length(qc_model.data)
    gc = qc_model.data[i]
    Γ = zeros(gc.n, gc.n)
    for k in 1:gc.m # loop over variance components
        Γ .+= qc_model.θ[k] .* gc.V[k]
    end
    math_Q += calculate_Qi(qc_model, gc, z, Γ, i)
end
@show math_Q

# autodiff Q
autodiff_loglikelihood(β) = QuasiCopula.loglikelihood(β, qc_model, z)
∇²logl = x -> ForwardDiff.hessian(autodiff_loglikelihood, x)
fullβ = [qc_model.β; qc_model.θ; 0.0]
Hfull = ∇²logl(fullβ)
auto_Q = -Hfull[end, end]
@show auto_Q;

auto_resβ_ij = [-0.09693671578820441, -0.07702396925952908, -0.1261277809575639, 0.04040177775644848, 0.04716318537196372]
math_resβ_ij = [-0.09693671578820436, -0.07702396925952905, -0.1261277809575638, 0.04040177775644851, 0.04716318537196369]


LoadError: UndefVarError: fdsa not defined

In [111]:
for i in 1:10
    # mathematical Q for 1 sample
    gc = qc_model.data[i]
    Γ = zeros(gc.n, gc.n)
    for k in 1:gc.m # loop over variance components
        Γ .+= qc_model.θ[k] .* gc.V[k]
    end
    Qi_math = calculate_Qi(qc_model, gc, z, Γ, i)

    # autodiff Q for 1 sample
    autodiff_loglikelihood_i(β) = loglikelihood_i(β, qc_model, z, i)
    ∇²logl_i = x -> ForwardDiff.hessian(autodiff_loglikelihood_i, x)
    fullβ = [qc_model.β; qc_model.θ; 0.0]
    Hfull_i = ∇²logl_i(fullβ)
    Qi_auto = -Hfull_i[end, end]
    
    @show Qi_math, Qi_auto, Qi_math - Qi_auto
end

auto_resβ_ij = [-0.09693671578820441, -0.07702396925952908, -0.1261277809575639, 0.04040177775644848, 0.04716318537196372]
math_resβ_ij = [-0.09693671578820436, -0.04435826891560527, -0.1261277809575638, 0.04040177775644851, 0.04716318537196369]


LoadError: UndefVarError: fdsa not defined

In [24]:
qc_model.∇β, qc_model.∇θ

([3.3382613090493507e-7, -8.106559831189131e-7, -1.3638758370460025e-6], [-6.708739634930794e-7, -1.8532789480829592e-7])

In [38]:
[qc_model.data[1].y qc_model.data[3].y qc_model.data[7].y  qc_model.data[2].y qc_model.data[4].y]

5×5 Matrix{Float64}:
 0.0  1.0  1.0  1.0  0.0
 0.0  1.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  1.0
 1.0  1.0  0.0  1.0  1.0
 1.0  1.0  0.0  1.0  1.0

In [46]:
[qc_model.data[1].q qc_model.data[3].q qc_model.data[7].q    qc_model.data[2].q qc_model.data[4].q]

2×5 Matrix{Float64}:
 3.07676  0.960326  11.9462   0.364994  0.218971
 2.39065  2.47697    6.80771  2.01004   2.17117

In [47]:
[qc_model.data[1].t qc_model.data[3].t qc_model.data[7].t    qc_model.data[2].t qc_model.data[4].t]

2×5 Matrix{Float64}:
 2.5  2.5  2.5  2.5  2.5
 2.5  2.5  2.5  2.5  2.5

In [45]:
[qc_model.data[1].η qc_model.data[3].η qc_model.data[7].η    qc_model.data[2].η qc_model.data[4].η]

5×5 Matrix{Float64}:
  0.247034   1.93406   0.987779  2.28029     0.0868077
 -0.212849   0.658095  1.13795   0.696106    0.743739
  0.773509   0.90897   0.827584  0.00790315  1.46994
  1.50333    0.618312  1.69343   0.265664    0.875086
  1.19385   -0.239743  1.44632   1.98587     0.69093

In [39]:
[qc_model.data[1].μ qc_model.data[3].μ qc_model.data[7].μ    qc_model.data[2].μ qc_model.data[4].μ]

5×5 Matrix{Float64}:
 0.561446  0.873698  0.728649  0.907231  0.521688
 0.446988  0.658832  0.757303  0.667324  0.677813
 0.684279  0.712789  0.695844  0.501976  0.813048
 0.818071  0.649835  0.844675  0.566028  0.705803
 0.76743   0.44035   0.809431  0.879305  0.666174

In [48]:
[qc_model.data[1].res qc_model.data[3].res qc_model.data[7].res    qc_model.data[2].res qc_model.data[4].res]

5×5 Matrix{Float64}:
 -1.13147    0.380211   0.610248   0.319773  -1.04436
 -0.899043   0.719609  -1.76646   -1.41631   -1.45044
 -1.47219   -1.57536    0.661138  -1.00396    0.47952
  0.47158    0.734066  -2.33197    0.875612   0.645621
  0.5505     1.12735   -2.06093    0.370488   0.707891

In [40]:
[qc_model.data[1].dμ qc_model.data[3].dμ qc_model.data[7].dμ    qc_model.data[2].dμ qc_model.data[4].dμ]

5×5 Matrix{Float64}:
 0.246224  0.11035   0.19772   0.0841628  0.24953
 0.24719   0.224772  0.183795  0.222003   0.218383
 0.216041  0.204721  0.211645  0.249996   0.152001
 0.148831  0.22755   0.131199  0.24564    0.207645
 0.178481  0.246442  0.154253  0.106127   0.222386

In [41]:
[qc_model.data[1].varμ qc_model.data[3].varμ qc_model.data[7].varμ    qc_model.data[2].varμ qc_model.data[4].varμ]

5×5 Matrix{Float64}:
 0.246224  0.11035   0.19772   0.0841628  0.24953
 0.24719   0.224772  0.183795  0.222003   0.218383
 0.216041  0.204721  0.211645  0.249996   0.152001
 0.148831  0.22755   0.131199  0.24564    0.207645
 0.178481  0.246442  0.154253  0.106127   0.222386

In [42]:
[qc_model.data[1].w1 qc_model.data[3].w1 qc_model.data[7].w1    qc_model.data[2].w1 qc_model.data[4].w1]

5×5 Matrix{Float64}:
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

In [43]:
[qc_model.data[1].w2 qc_model.data[3].w2 qc_model.data[7].w2    qc_model.data[2].w2 qc_model.data[4].w2]

5×5 Matrix{Float64}:
 0.246224  0.11035   0.19772   0.0841628  0.24953
 0.24719   0.224772  0.183795  0.222003   0.218383
 0.216041  0.204721  0.211645  0.249996   0.152001
 0.148831  0.22755   0.131199  0.24564    0.207645
 0.178481  0.246442  0.154253  0.106127   0.222386

## $d_{\beta} d_{\tau}$  and $d_\tau d_\theta$ for Gaussian case

A_mul_B! suddenly can't be autodiffed, so I decided it's too hard to check.

In [111]:
function loglikelihood(τ::T, gcm::GaussianCopulaVCModel) where T
    θ = gcm.θ
    β = gcm.β
    # allocate vector of type T
    n, p = size(gcm.data[1].X)
    μ = zeros(T, n)
    res = zeros(T, n)
    storage_n = zeros(T, n)
    q = zeros(T, length(θ))
    logl = zero(T)
    for gc in gcm.data
        X = gc.X
        y = gc.y
        n, p = size(X)
        sqrtτ = sqrt(abs(τ))
        # update_res! step (need to avoid BLAS)
        A_mul_b!(μ, X, β)
        for i in 1:gc.n
            res[i] = y[i] - μ[i]
        end
        # standardize_res! step
        res .*= sqrtτ
        rss  = abs2(norm(res)) # RSS of standardized residual
        tsum = dot(θ, gc.t) # ben: why is there abs here?
        logl += - log(1 + tsum) - (gc.n * log(2π) -  gc.n * log(abs(τ)) + rss) / 2
        # update Γ
        @inbounds for k in 1:gc.m
            A_mul_b!(storage_n, gc.V[k], res)
            q[k] = dot(res, storage_n) / 2 # q[k] = 0.5 r' * V[k] * r (update variable b for variance component model)
        end
        qsum  = dot(θ, q)
        logl += log(1 + qsum)
    end
    return logl
end
function A_mul_b!(c::AbstractVector{T}, A::AbstractMatrix, b::AbstractVector) where T
    n, p = size(A)
    fill!(c, zero(T))
    for j in 1:p, i in 1:n
        c[i] += A[i, j] * b[j]
    end
    return c
end
function At_mul_b!(c::AbstractVector{T}, A::AbstractMatrix, b::AbstractVector) where T
    n, p = size(A)
    fill!(c, zero(T))
    for j in 1:p, i in 1:n
        c[j] += A[i, j] * b[i]
    end
    return c
end
function get_Hτβ(qc_model::GaussianCopulaVCModel)
    β = qc_model.β
    θ = qc_model.θ
    τ = qc_model.τ[1]
    T = eltype(β)
    Hτβ = zeros(T, length(β))
    Hτβstore = zeros(T, length(β))
    for qc in qc_model.data
        fill!(Hτβstore, 0)
        # compute Hτβstore = sqrt(τ)X'Γ(y-Xb)
        for k in 1:qc.m
            mul!(gc.storage_n, gc.V[k], gc.res) # storage_n = V[k] * res = V[k] * (y-Xb) * sqrt(τ) 
            BLAS.gemv!('T', θ[k], qc.X, qc.storage_n, one(T), Hτβstore) # Hτβstore = sqrt(τ)θ[k]X'V[k](y-Xb)
        end
        qsum = dot(θ, qc.q) # qsum = 0.5r(β)*Γ*r(β) where r = (y-Xb) * sqrt(τ)
        denom = abs2(1 + qsum) # denom = (1 + 0.5τ(y-Xb)'Γ(y-Xb) )^2
        BLAS.gemv!('T', one(T), qc.X, qc.res, -inv(denom), Hτβstore) # Hτβstore = -sqrt(τ)X'Γ(y-Xb) / denom + X'(y-Xb)sqrt(τ)
        Hτβstore ./= sqrt(τ)
        Hτβ .+= Hτβstore
    end
    return Hτβ
end
function get_Hτθ(qc_model::GaussianCopulaVCModel)
    θ = qc_model.θ
    m = length(θ)
    T = eltype(θ)
    Hτθ = zeros(T, m)
    qstore = zeros(T, m)
    for qc in qc_model.data
        copyto!(qstore, qc.q) # gc.q = 0.5r(β)*V[k]*r(β) where r = (y-Xb) * sqrt(τ)
        qstore ./= qc_model.τ[1]
        Hτθ .+= inv(1 + dot(θ, qstore)) .* qstore
    end
    return Hτθ
end
function get_Hτθ(τ, θ, qc_model::GaussianCopulaVCModel)
    qc_model.τ[1] = τ
    qc_model.θ .= θ
    return get_Hτθ(qc_model)
end


get_Hτθ (generic function with 3 methods)

In [106]:
# need autodiff friendly function to compute ∇θlogl, and use autodiff to compute ∇τ∇θlogl
function autodiff_∇θlogl(τ, qc_model::GaussianCopulaVCModel)
    T = eltype(τ)
    β = qc_model.β
    θ = qc_model.θ
    ∇θ = zeros(T, length(θ))
    n, p = size(qc_model.data[1].X)
    μ = zeros(T, n)
    res = zeros(T, n)
    for gc in qc_model.data
        sqrtτ = sqrt(abs(τ))
        # update_res! step (need to avoid BLAS)
        A_mul_b!(μ, gc.X, β)
        for i in 1:gc.n
            res[i] = gc.y[i] - μ[i]
        end
        # standardize_res! step
        res .*= sqrtτ        
        rss  = abs2(norm(res))
        tsum = dot(abs.(θ), gc.t)
        @inbounds for k in 1:gc.m
            A_mul_b!(gc.storage_n, gc.V[k], res) # storage_n = V[k] * res = V[k] * (y-Xb) * sqrt(τ) 
#             BLAS.gemv!('T', θ[k], gc.X, gc.storage_n, one(T), gc.∇β)
            gc.storage_n .*= θ[k]
            ∇β_new = zeros(T, length(gc.∇β))
            At_mul_b!(∇β_new, gc.X, gc.storage_n)
            gc.∇β .+= ∇β_new
            gc.q[k] = dot(res, gc.storage_n) / 2 # gc.q = 0.5 res' * V[k] * res = 0.5τ(y-Xb)^t*V*(y-Xb)
        end
        qsum  = dot(θ, gc.q) # qsum = 0.5r(β)*Γ*r(β) where r = (y-Xb) * sqrt(τ)
        inv1pq = inv(1 + qsum)
        ∇θ .+= inv1pq .* gc.q .- inv(1 + tsum) .* gc.t
    end
    return qc_model.∇θ
end

# mathematical function to evaluate ∇θlogl
function get_∇θlogl(τ, qc_model::GaussianCopulaVCModel)
    qc_model.τ[1] = τ
    loglikelihood!(qc_model, true, true)
    return qc_model.∇θ
end

# ensure autodiff friendly ∇θlogl is correct
τ = 10.0
@show get_∇θlogl(τ, qc_model)
@show autodiff_∇θlogl(τ, qc_model);

get_∇θlogl(τ, qc_model) = [74.16961784140449, -51.7010522377855]
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64
T = Float64

In [110]:
autodiff_∇θ(τ) = autodiff_∇θlogl(τ, qc_model)
get_Hτθ_autodiff = τ -> ForwardDiff.derivative(autodiff_∇θ, τ)

τ = 10.0

# Hθτ by math
# Hθτ = get_Hτθ(τ, qc_model)

# Hθτ by autodiff
Hθτ_autodiff = get_Hτθ_autodiff(τ)

T = ForwardDiff.Dual{ForwardDiff.Tag{typeof(autodiff_∇θ), Float64}, Float64, 1}
T = Float64


LoadError: MethodError: no method matching Float64(::ForwardDiff.Dual{ForwardDiff.Tag{typeof(autodiff_∇θ), Float64}, Float64, 1})
Closest candidates are:
  (::Type{T})(::Real, ::RoundingMode) where T<:AbstractFloat at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/base/rounding.jl:200
  (::Type{T})(::T) where T<:Number at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/base/boot.jl:770
  (::Type{T})(::VectorizationBase.Double{T}) where T<:Union{Float16, Float32, Float64, VectorizationBase.Vec{<:Any, <:Union{Float16, Float32, Float64}}, VectorizationBase.VecUnroll{var"#s36", var"#s35", var"#s34", V} where {var"#s36", var"#s35", var"#s34"<:Union{Float16, Float32, Float64}, V<:Union{Bool, Float16, Float32, Float64, Int16, Int32, Int64, Int8, UInt16, UInt32, UInt64, UInt8, SIMDTypes.Bit, VectorizationBase.AbstractSIMD{var"#s35", var"#s34"}}}} at ~/.julia/packages/VectorizationBase/wy5gX/src/special/double.jl:100
  ...

In [ ]:
β = [γ; τ] Hγτ

In [36]:
# Hθτ by math
Hθτ = get_Hτβ(qc_model)

3-element Vector{Float64}:
 -45.28094257865774
  20.433982724328743
 -64.2636673294168

# Compute Hessian blocks via `ForwardDiff.jl`

Computing full Hessian with autodiff

In [36]:
using ForwardDiff, BenchmarkTools

function f(y::AbstractVector, X::AbstractMatrix, β::AbstractVector)
    0.5*sum(abs2, y - X*β)
end
f(β::AbstractVector) = f(y, X, β)
f(y::AbstractVector, X::AbstractMatrix, β1, β2) = f(y, X, [β1; β2])
f1(β1) = f(y, X, β1, β2)
f2(β2) = f(y, X, β1, β2)

n = 10_000
p = 15
X = randn(n, p)
y = randn(n)
β = randn(p)
β1 = β[1:end-1]
β2 = β[end]

Gcfg = ForwardDiff.GradientConfig(f, β)
Hcfg = ForwardDiff.HessianConfig(f, β)
Hcfg1 = ForwardDiff.HessianConfig(f, β, ForwardDiff.Chunk{1}())
Hcfg4 = ForwardDiff.HessianConfig(f, β, ForwardDiff.Chunk{4}())
Hcfg10 = ForwardDiff.HessianConfig(f, β, ForwardDiff.Chunk{10}())
Hcfg15 = ForwardDiff.HessianConfig(f, β, ForwardDiff.Chunk{15}())

# analytical gradient and Hessian
grad_true = -X'*(y-X*β)
hess_true = X'*X

# autodiff full Hessian
storage = similar(hess_true)
∇²f(x) = ForwardDiff.hessian(f, x, Hcfg)
∇²f!(storage, x) = ForwardDiff.hessian!(storage, f, x, Hcfg)
∇²f1!(storage, x) = ForwardDiff.hessian!(storage, f, x, Hcfg1)
∇²f4!(storage, x) = ForwardDiff.hessian!(storage, f, x, Hcfg4)
∇²f10!(storage, x) = ForwardDiff.hessian!(storage, f, x, Hcfg10)
∇²f15!(storage, x) = ForwardDiff.hessian!(storage, f, x, Hcfg15)
@btime ∇²f($β)
@btime ∇²f!($storage, $β)
@btime ∇²f1!($storage, $β)
@btime ∇²f4!($storage, $β)
@btime ∇²f10!($storage, $β)
@btime ∇²f15!($storage, $β)
@show all(∇²f(β) .≈ hess_true)
@show all(storage .≈ hess_true)
∇²f(β)

  43.531 ms (27 allocations: 49.46 MiB)
  43.551 ms (25 allocations: 49.45 MiB)
  33.405 ms (1143 allocations: 137.36 MiB)
  20.294 ms (87 allocations: 61.04 MiB)
  64.475 ms (25 allocations: 73.88 MiB)
  26.903 ms (9 allocations: 39.13 MiB)
all(∇²f(β) .≈ hess_true) = true
all(storage .≈ hess_true) = true


15×15 Matrix{Float64}:
 9939.65     -124.641     -119.696    …   -24.3604    -10.6148     -2.25382
 -124.641    9943.05       -75.9184       -68.8597    -20.495      96.8995
 -119.696     -75.9184    9976.93        -122.128      68.9673    -89.0699
   59.9671    193.139      -56.8702       -60.795     170.943     108.837
  -63.1657    -35.5671      77.667        -91.7288   -237.139      47.7764
  -49.074     -95.9046     137.558    …   -19.7223    -22.0753    -55.465
  -43.2553    -86.3246      -3.96029     -113.709     -23.4215    110.93
  -43.3568     73.3477    -135.155         80.3859    -58.9502    -18.0456
   -7.33843    48.2796     -88.2863       -90.3122    -22.2314    161.907
  -41.0803     -0.092209   -42.5719        44.4396    109.356     -85.4449
   92.1459    -30.6379     123.655    …    34.8926     75.911     104.646
   91.1883    -61.0799      39.3923      -167.302     156.966     -25.9196
  -24.3604    -68.8597    -122.128       9786.45     -144.498      58.1439
  -10.6

In [2]:
# autodiff full gradient
∇f(x) = ForwardDiff.gradient(f, x)
∇f(β)

15-element Vector{Float64}:
  -14202.968665559405
  129692.33237650341
  -66183.26762923645
   27523.27568838293
   76586.76838533783
  -18929.453717086988
    1830.9415727628884
  -74010.51410300462
  -80901.97902831406
   72414.3798976783
  185310.5629582686
  -99232.70814879308
   -3144.8381675157434
     112.25510780112529
 -114361.67580969108

In [13]:
# W term
function hessian_column(β)
    function element_derivative(β)
        β1 = @view(β[1:end-1])
        β2 = β[end]
        return ForwardDiff.derivative(β2 -> f(y,X,β1,β2), β2)
    end
    ForwardDiff.gradient(element_derivative, β)
end

@time H1 = ForwardDiff.hessian(f, β)
@time H1 = ForwardDiff.hessian(f, β)
@time H2 = hessian_column(β)
@time H2 = hessian_column(β)
@show all(H2 .≈ H1[:, end]);

  0.057861 seconds (30 allocations: 49.472 MiB, 1.28% gc time)
  0.040010 seconds (30 allocations: 49.472 MiB, 1.37% gc time)
  0.596121 seconds (1.99 M allocations: 136.797 MiB, 3.58% gc time, 98.29% compilation time)
  0.001236 seconds (70 allocations: 5.504 MiB)
all(H2 .≈ H1[:, end]) = true


In [41]:
# R term
get_grad_last(β2::Number) = ForwardDiff.derivative(f2, β2)
get_grad_last(β2) ≈ grad_true[end]

true

In [40]:
# Q term
get_hess_last(β2) = ForwardDiff.derivative(β2 -> ForwardDiff.derivative(f2, β2), β2)
@show get_hess_last(β2) ≈ hess_true[end, end]

get_hess_last(β2) ≈ hess_true[end, end] = true


true

In [37]:
# P term
get_hess_first(x) = ForwardDiff.hessian(f1, x)
all(get_hess_first(β1) .≈ hess_true[1:end-1, 1:end-1])

true

In [38]:
ForwardDiff.hessian(f1, β1)

14×14 Matrix{Float64}:
 9939.65     -124.641     -119.696    …    91.1883   -24.3604    -10.6148
 -124.641    9943.05       -75.9184       -61.0799   -68.8597    -20.495
 -119.696     -75.9184    9976.93          39.3923  -122.128      68.9673
   59.9671    193.139      -56.8702        63.7427   -60.795     170.943
  -63.1657    -35.5671      77.667        105.74     -91.7288   -237.139
  -49.074     -95.9046     137.558    …   107.755    -19.7223    -22.0753
  -43.2553    -86.3246      -3.96029      101.021   -113.709     -23.4215
  -43.3568     73.3477    -135.155        -86.6973    80.3859    -58.9502
   -7.33843    48.2796     -88.2863       -31.7601   -90.3122    -22.2314
  -41.0803     -0.092209   -42.5719       105.311     44.4396    109.356
   92.1459    -30.6379     123.655    …    32.7042    34.8926     75.911
   91.1883    -61.0799      39.3923      9996.45    -167.302     156.966
  -24.3604    -68.8597    -122.128       -167.302   9786.45     -144.498
  -10.6148    -20.495 

# Use `FastDifferentiation.jl` to compute W

Building the jacobian takes the longest. 

+ $n=100$: `jacobian` takes 7.2 sec, building W takes ~0.000020 sec
+ $n=1000$: `jacobian` takes 617 sec, building W takes ~0.000046 sec
+ $n=10,000$: `jacobian` takes  sec, building W takes  sec
+ $n=100,000$: `jacobian` takes  sec, building W takes  sec

In [184]:
using FastDifferentiation
using BenchmarkTools

function f(y::AbstractVector, X::AbstractMatrix, β::AbstractVector)
    0.5*sum(abs2, y - X*β)
end
f(β::AbstractVector) = f(y, X, β)
function f(y::AbstractVector, X::AbstractMatrix, z::AbstractVector, β1::AbstractVector, β2::Number)
    0.5*sum(abs2, y - X*β1 - z*β2)
end
f(β2::AbstractVector, z::AbstractVector) = f(y, X, z, β1, β2)

function test(n::Int)

    # simulate data
    p = 15
    βsym = make_variables(:βsym, p)
    X = randn(n, p-1)
    z = randn(n)
    fullX = [X z]
    y = randn(n)
    β = randn(p)

    # compute autodiff Hessian
    @time βsym = make_variables(:βsym, p)
    @time zsym = make_variables(:zsym, n)
    @time jac = jacobian([f(y,X,zsym,βsym[1:end-1],βsym[end])], [βsym[p]])     # compute last element of Jacobian
    @time last_hess_col = vec(jacobian(vec(jac), βsym))      # compute last column of Hessian
    @time hess_func! = make_function(last_hess_col, [βsym; zsym], in_place=true)
    resmat = similar(last_hess_col, Float64)
    parameters = [β; z]
    @time hess_func!(resmat, parameters)
    @show all(resmat .≈ (fullX'*fullX)[:, p])

    # change snp value and recompute Hessian
    z .= randn(n)
    parameters[length(β)+1:end] .= z
    @time hess_func!(resmat, parameters)

    # check answer is correcct
    fullX = [X z]
    @show all(resmat .≈ (fullX'*fullX)[:, p]);
end

test (generic function with 1 method)

In [185]:
test(100)

  0.000149 seconds (166 allocations: 5.797 KiB)
  0.000536 seconds (1.10 k allocations: 38.375 KiB)
  7.973626 seconds (47.92 M allocations: 850.979 MiB, 11.36% gc time)
  1.206508 seconds (8.66 M allocations: 260.055 MiB)
  0.148661 seconds (1.04 M allocations: 23.633 MiB)
  0.540932 seconds (837.00 k allocations: 43.686 MiB, 99.80% compilation time)
all(resmat .≈ (fullX' * fullX)[:, p]) = true
  0.000008 seconds (1 allocation: 16 bytes)
all(resmat .≈ (fullX' * fullX)[:, p]) = true


true

In [186]:
test(1000)

  0.000050 seconds (166 allocations: 5.797 KiB)
  0.004286 seconds (11.00 k allocations: 382.945 KiB)
657.217390 seconds (4.24 G allocations: 65.440 GiB, 3.31% gc time)
 97.831442 seconds (609.65 M allocations: 11.400 GiB, 2.84% gc time)
 13.750565 seconds (82.45 M allocations: 1.302 GiB, 5.76% gc time)
 20.263622 seconds (8.63 M allocations: 436.248 MiB, 99.96% compilation time)
all(resmat .≈ (fullX' * fullX)[:, p]) = true
  0.000046 seconds (1 allocation: 16 bytes)
all(resmat .≈ (fullX' * fullX)[:, p]) = true


true

In [187]:
test(10000)

  0.000125 seconds (166 allocations: 5.797 KiB)
  0.019304 seconds (110.00 k allocations: 3.807 MiB)
5961.380287 seconds (27.70 G allocations: 523.336 GiB, 10.77% gc time, 0.01% compilation time)


LoadError: InterruptException:

In [181]:
# change snp value and recompute Hessian
z .= randn(n)
parameters[length(β)+1:end] .= z
@time hess_func!(resmat, parameters)

# check answer is correcct
fullX = [X z]
@show all(resmat .≈ (fullX'*fullX)[:, p]);

LoadError: DimensionMismatch: array could not be broadcast to match destination

In [182]:
resmat

15-element Vector{Float64}:
  -4.114010353070302
 -12.661463023912697
   2.25509924885527
  -1.0013572459106406
  15.793009164107763
 -14.868073789235831
  -4.155792022593147
  -7.68690634705341
   5.45451982859588
  -3.603230339806478
   5.237637781123744
  -6.8140226019864105
   4.145507274108481
  -4.769000792200294
  81.58060789024084

In [183]:
@time fullX'*fullX

  0.000933 seconds (2 allocations: 2.000 KiB)


15×15 Matrix{Float64}:
 10191.5       -96.2596    -256.035   …    32.9493    -94.7449    141.446
   -96.2596   9944.36       -56.9665       52.128     -26.4597    130.803
  -256.035     -56.9665   10134.9          43.7884    -65.8664    -94.43
     2.27271  -193.134     -177.173        73.1183    -57.4444     48.5885
  -174.179      23.5058     -42.5377      -90.2728    -54.5613     38.1422
   -29.8089    -21.1211      23.0902  …    54.7346   -108.574     208.877
   -51.329     -37.9485    -198.043       -84.0166    -71.9338    -30.7436
    65.3011   -127.397       10.2281      161.35       57.238     309.319
    88.6454    -33.209       12.6626       41.1088     -9.22229  -107.492
   -10.2634     97.4277      20.0129      -47.3538    -87.7534     70.0365
   171.365     -26.6669      11.2007  …    34.0573     83.5161    -60.8001
     6.05323     4.05051   -182.542       -62.499     -22.6775    123.392
    32.9493     52.128       43.7884     9986.05       72.7584   -215.99
   -94.7449 