# Form the NB Regression Random Intercept Model: Simulated set

Next we may try joint estimation using Newton's + IPOPT. 

    I create new structures `NBCopulaVCObs`, `NBCopulaVCModel`
    



In [1]:
using Revise
using DataFrames, Random, GLM, GLMCopula
using ForwardDiff, Test, LinearAlgebra
using LinearAlgebra: BlasReal, copytri!

Random.seed!(1234)

# sample size
N = 10000
# observations per subject
n = 5

variance_component_1 = 0.1
variance_component_2 = 0.5

r = 10
p = 0.7
μ = r * (1-p) * inv(p)

# var = r * (1-p) * inv(p^2)

# true beta
β_true = log(μ)

dist = NegativeBinomial

Γ = variance_component_1 * ones(n, n) + variance_component_2 * Matrix(I, n, n)
vecd = [dist(r, p) for i in 1:n]
nonmixed_multivariate_dist = NonMixedMultivariateDistribution(vecd, Γ)

Y_Nsample = simulate_nobs_independent_vectors(nonmixed_multivariate_dist, N)

┌ Info: Precompiling Revise [295af30f-e4ad-537b-8983-00126c2a3abe]
└ @ Base loading.jl:1317
┌ Info: Precompiling GLMCopula [c47b6ae2-b804-4668-9957-eb588c99ffbc]
└ @ Base loading.jl:1317
┌ Info: Precompiling ForwardDiff [f6369f11-7733-5829-9624-2563aa707210]
└ @ Base loading.jl:1317


10000-element Vector{Vector{Float64}}:
 [2.0, 1.0, 2.0, 6.0, 1.0]
 [8.0, 5.0, 3.0, 5.0, 2.0]
 [2.0, 4.0, 4.0, 10.0, 2.0]
 [4.0, 3.0, 7.0, 4.0, 8.0]
 [10.0, 10.0, 9.0, 1.0, 1.0]
 [4.0, 4.0, 3.0, 4.0, 3.0]
 [9.0, 6.0, 5.0, 4.0, 4.0]
 [6.0, 1.0, 3.0, 6.0, 0.0]
 [4.0, 7.0, 3.0, 3.0, 3.0]
 [5.0, 5.0, 3.0, 6.0, 2.0]
 [7.0, 6.0, 5.0, 2.0, 3.0]
 [3.0, 2.0, 7.0, 1.0, 4.0]
 [2.0, 3.0, 2.0, 2.0, 6.0]
 ⋮
 [2.0, 3.0, 1.0, 4.0, 2.0]
 [1.0, 3.0, 6.0, 2.0, 2.0]
 [2.0, 1.0, 3.0, 5.0, 1.0]
 [2.0, 3.0, 1.0, 1.0, 5.0]
 [2.0, 3.0, 4.0, 4.0, 10.0]
 [2.0, 3.0, 6.0, 2.0, 6.0]
 [2.0, 3.0, 1.0, 8.0, 2.0]
 [8.0, 0.0, 6.0, 3.0, 5.0]
 [5.0, 3.0, 2.0, 3.0, 6.0]
 [5.0, 6.0, 6.0, 9.0, 5.0]
 [0.0, 2.0, 1.0, 4.0, 3.0]
 [3.0, 6.0, 1.0, 3.0, 3.0]

In [2]:
d = NegativeBinomial()
link = LogLink()
D = typeof(d)
Link = typeof(link)
T = Float64
gcs = Vector{NBCopulaVCObs{T, D, Link}}(undef, N)
for i in 1:N
    y = Float64.(Y_Nsample[i])
    X = ones(n, 1)
    V = [ones(n, n), Matrix(I, n, n)]
    gcs[i] = NBCopulaVCObs(y, X, V, d, link)
end
gcm = NBCopulaVCModel(gcs);
# gcm.r[1] = r

In [3]:
initialize_model!(gcm)
@show gcm.β
# @show gcm.Σ
@show gcm.r

Initializing NegBin r to Poisson regression values
initializing β using Newton's Algorithm under Independence Assumption
1 0.0 -124348.27381045274 39999
2 -124348.27381045274 -124348.27381045274 39999
initializing variance components using MM-Algorithm
gcm.Σ = [220.41649889527125, 1469.9374107479462]
hiiii gcmPoisson.Σ = [220.41649889527125, 1469.9374107479462]
gcm.θ = [-7.661495143796714, 219.50634778984383, 1476.6337551112845]
gcm.θ = [1.505897960765723, 220.41649889527125, 1469.9374107479462]
gcm.θ = [1.505897960765723, 220.41649889527125, 1469.9374107479462]

******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt
******************************************************************************

This is Ipopt version 3.12.10, running with

1-element Vector{Float64}:
 5.567431570219433

In [4]:
β_true

1.4552872326068422

Initialize β and σ2, here I just copy the solution for β and σ2 from MixedModels.jl over

In [5]:
GLMCopula.loglikelihood!(gcm, true, true)

-119242.84209292504

## Try Quasi-Newton after specifying gradient of r

to-do: 

1. added field $r$ to model structure $gcm.r$, change access to r this way instead of through the distribution
2. add $gc.\nabla r$ in loglikelihood function


## Newton after specifying the hessian term too

3. add $gc.Hr$ in loglikelihood function

In [6]:
# Quasi-Newton
@time GLMCopula.fit!(gcm, IpoptSolver(print_level = 5, max_iter = 100,
#     tol = 10^-6, mu_strategy = "adaptive", mu_oracle = "loqo",
#     mehrotra_algorithm="yes", warm_start_init_point="yes",
    hessian_approximation = "limited-memory"))

This is Ipopt version 3.12.10, running with linear solver mumps.
NOTE: Other linear solvers might be more efficient (see Ipopt documentation).

Number of nonzeros in equality constraint Jacobian...:        0
Number of nonzeros in inequality constraint Jacobian.:        0
Number of nonzeros in Lagrangian Hessian.............:        0

Total number of variables............................:        4
                     variables with only lower bounds:        3
                variables with lower and upper bounds:        0
                     variables with only upper bounds:        0
Total number of equality constraints.................:        0
Total number of inequality constraints...............:        0
        inequality constraints with only lower bounds:        0
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:        0

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0 

┌ Warning: Optimization unsuccesful; got UserLimit
└ @ GLMCopula /Users/biona001/.julia/dev/GLMCopula/src/parameter_estimation/fit_nb.jl:30


-119223.41000659589

In [7]:
println("estimated β = $(gcm.β[1]); true β = $β_true")
println("estimated variance component 1 = $(gcm.Σ[1]); true variance component 1 = $variance_component_1")
println("estimated variance component 2 = $(gcm.Σ[2]); true variance component 2 = $variance_component_2")
println("estimated r = $(gcm.r[1]); true r = $r");

estimated β = 1.498426817715401; true β = 1.4552872326068422
estimated variance component 1 = 0.02674691919391171; true variance component 1 = 0.1
estimated variance component 2 = 1.888827175699426e-9; true variance component 2 = 0.5
estimated r = 5.9362402820448; true r = 10


In [26]:
println("estimated β = $(gcm.β[1]); true β = $β_true")
println("estimated variance component 1 = $(gcm.Σ[1]); true variance component 1 = $variance_component_1")
println("estimated variance component 2 = $(gcm.Σ[2]); true variance component 2 = $variance_component_2")
println("estimated r = $(gcm.r[1]); true r = $r");

estimated β = 1.4379838410795471; true β = 1.4552872326068422
estimated variance component 1 = 76.15550890783125; true variance component 1 = 0.1
estimated variance component 2 = 594.7840729601483; true variance component 2 = 0.5
estimated r = 8.576615711834037; true r = 10


In [24]:
println("estimated β = $(gcm.β[1]); true β = $β_true")
println("estimated variance component 1 = $(gcm.Σ[1]); true variance component 1 = $variance_component_1")
println("estimated variance component 2 = $(gcm.Σ[2]); true variance component 2 = $variance_component_2")
println("estimated r = $(gcm.r[1]); true r = $r");

estimated β = 6.060725021632323; true β = 6.060457418594933
estimated variance component 1 = 0.07105008828138462; true variance component 1 = 0.1
estimated variance component 2 = 0.27759738195773537; true variance component 2 = 0.5
estimated r = 851.6296619446404; true r = 1000


In [12]:
println("estimated β = $(gcm.β[1]); true β = $β_true")
println("estimated variance component 1 = $(gcm.Σ[1]); true variance component 1 = $variance_component_1")
println("estimated variance component 2 = $(gcm.Σ[2]); true variance component 2 = $variance_component_2")
println("estimated r = $(gcm.r[1]); true r = $r");

estimated β = 3.758024524976841; true β = 3.757872325600888
estimated variance component 1 = 0.1378138994600511; true variance component 1 = 0.1
estimated variance component 2 = 0.7354212501202747; true variance component 2 = 0.5
estimated r = 96.89896572074814; true r = 100


In [69]:
println("estimated β = $(gcm.β[1]); true β = $β_true")
println("estimated variance component 1 = $(gcm.Σ[1]); true variance component 1 = $variance_component_1")
println("estimated variance component 2 = $(gcm.Σ[2]); true variance component 2 = $variance_component_2")
println("estimated r = $(gcm.r[1]); true r = $r");

estimated β = 1.454302942507524; true β = 1.4552872326068422
estimated variance component 1 = 0.16080189197837352; true variance component 1 = 0.1
estimated variance component 2 = 0.8976070963094536; true variance component 2 = 0.5
estimated r = 11.367324765405236; true r = 10


In [62]:
println("estimated β = $(gcm.β[1]); true β = $β_true")
println("estimated variance component 1 = $(gcm.Σ[1]); true variance component 1 = $variance_component_1")
println("estimated variance component 2 = $(gcm.Σ[2]); true variance component 2 = $variance_component_2")
println("estimated r = $(gcm.r[1]); true r = $r");

estimated β = 1.0866771907017754; true β = 1.09861228866811
estimated variance component 1 = 0.16508355574885977; true variance component 1 = 0.1
estimated variance component 2 = 1.0080802223132954; true variance component 2 = 0.5
estimated r = 8.138290481765807; true r = 7


**If initializing VCs to 1**:
+ With true $r = 1$
    - good estimates of $\beta$, VC parameters, and r
    - sometimes does crazy line search. 
+ With true $r = 2$
    - VC parameters goes to 0, esimated $\beta$ is wrong, and estimated r is 1.17. 

**If initializing VCs by update_$\Sigma$**:
+ With true $r = 1$
    - one VC parameters becomes basically 0 after initialization
    - bad estimated beta (-0.45 vs -0.84 truth)
    - estimated VC = 0.0 and 0.69 (truth = 0.1 and 0.5)
    - estimated r = 1.1

## Newton

In [8]:
@time GLMCopula.fit!(gcm, IpoptSolver(print_level = 5, max_iter = 100, 
    tol = 10^-6, mu_strategy = "adaptive", mu_oracle = "loqo",
    hessian_approximation = "exact"))

This is Ipopt version 3.12.10, running with linear solver mumps.
NOTE: Other linear solvers might be more efficient (see Ipopt documentation).

Number of nonzeros in equality constraint Jacobian...:        0
Number of nonzeros in inequality constraint Jacobian.:        0
Number of nonzeros in Lagrangian Hessian.............:        5

Total number of variables............................:        4
                     variables with only lower bounds:        3
                variables with lower and upper bounds:        0
                     variables with only upper bounds:        0
Total number of equality constraints.................:        0
Total number of inequality constraints...............:        0
        inequality constraints with only lower bounds:        0
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:        0

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0 

┌ Warning: Optimization unsuccesful; got UserLimit
└ @ GLMCopula /Users/biona001/.julia/dev/GLMCopula/src/parameter_estimation/fit_nb.jl:30


-118498.19010251868

In [9]:
println("estimated β = $(gcm.β[1]); true β = $β_true")
println("estimated variance component 1 = $(gcm.Σ[1]); true variance component 1 = $variance_component_1")
println("estimated variance component 2 = $(gcm.Σ[2]); true variance component 2 = $variance_component_2")
println("estimated r = $(gcm.r[1]); true r = $r");

estimated β = 1.431700604659203; true β = 1.4552872326068422
estimated variance component 1 = 0.14165778449786529; true variance component 1 = 0.1
estimated variance component 2 = 0.5807584133259613; true variance component 2 = 0.5
estimated r = 5.676937046097018; true r = 10


In [10]:
gcm.∇θ

4-element Vector{Float64}:
 2121.5670801354186
  -71.10375733934279
   12.900327891814868
  443.90634061495734